"""
ThreatGraph Report Generator
Produces a structured markdown/text incident report.
"""

from __future__ import annotations
from datetime import datetime
from .correlator import AttackGraph, STAGE_ORDER


def generate_report(
    attack_graph: AttackGraph,
    ai_result: dict,
    filename: str | None = None,
) -> str:
    """
    Returns a formatted markdown incident report string.
    Optionally writes it to `filename`.
    """
    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")
    severity = ai_result.get("severity", "Unknown")
    attack_type = ai_result.get("attack_type", "Unknown")
    explanation = ai_result.get("explanation", "")
    recommendations = ai_result.get("recommendations", [])

    severity_emoji = {
        "Critical": "🔴",
        "High": "🟠",
        "Medium": "🟡",
        "Low": "🟢",
    }.get(severity, "⚪")

    lines = [
        "# ThreatGraph Incident Report",
        f"**Generated:** {now}",
        "",
        "---",
        "",
        "## Executive Summary",
        "",
        f"| Field | Value |",
        f"|-------|-------|",
        f"| **Severity** | {severity_emoji} {severity} |",
        f"| **Attack Type** | {attack_type} |",
        f"| **Attacker IP** | `{attack_graph.attacker_ip or 'Unknown'}` |",
        f"| **Affected User** | `{attack_graph.affected_user or 'Unknown'}` |",
        f"| **Timeline Start** | {str(attack_graph.timeline_start)[:19] if attack_graph.timeline_start else 'N/A'} |",
        f"| **Timeline End** | {str(attack_graph.timeline_end)[:19] if attack_graph.timeline_end else 'N/A'} |",
        f"| **Stages Observed** | {', '.join(attack_graph.stages_observed) or 'None'} |",
        "",
        "---",
        "",
        "## Attack Chain",
        "",
    ]

    for i, node in enumerate(attack_graph.nodes, 1):
        mitre_str = ""
        if node.mitre:
            mitre_str = " — " + ", ".join(f"`{t[0]}`" for t in node.mitre)
        lines.append(f"{i}. **[{node.stage}]** {node.label}{mitre_str}")

    lines += [
        "",
        "---",
        "",
        "## MITRE ATT&CK Techniques",
        "",
        "| Technique ID | Name | Stage |",
        "|-------------|------|-------|",
    ]

    seen_techniques: set[str] = set()
    for node in attack_graph.nodes:
        for tid, tname in node.mitre:
            if tid not in seen_techniques:
                seen_techniques.add(tid)
                lines.append(f"| `{tid}` | {tname} | {node.stage} |")

    lines += [
        "",
        "---",
        "",
        "## AI Analysis",
        "",
        explanation,
        "",
        "---",
        "",
        "## Recommended Response Actions",
        "",
    ]

    for i, rec in enumerate(recommendations, 1):
        lines.append(f"{i}. {rec}")

    lines += [
        "",
        "---",
        "",
        "## Detailed Event Log",
        "",
        "| # | Time | Stage | Event | Source IP | Destination | User |",
        "|---|------|-------|-------|-----------|-------------|------|",
    ]

    for i, node in enumerate(attack_graph.nodes, 1):
        ts = str(node.timestamp)[:19]
        src = node.src_ip or ""
        dst = node.dst_ip or ""
        user = node.user or ""
        lines.append(f"| {i} | {ts} | {node.stage} | {node.label} | {src} | {dst} | {user} |")

    lines += [
        "",
        "---",
        "",
        f"*Report generated by ThreatGraph — Autonomous Threat Investigation Engine*",
    ]

    report = "\n".join(lines)

    if filename:
        with open(filename, "w", encoding="utf-8") as f:
            f.write(report)

    return report
